dist: trusty

jobs:
  include:
    - stage: deploy to k8s
      before_script:
      - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      script:
      - kubectl apply -f k8s.yaml

      