dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - docker build -t kuperiu/litecoin:0.18.1 .
      - docker push kuperiu/litecoin:0.18.1

      